some = input("Digite algo")
print("A expressão: ",some,", pode ser um alfanumérico? ",some.isalnum())
print("A expressão: ",some,", pode ser uma letra ",some.isalpha())
print("A expressão: ",some,", pode estar em maiúsculo? ",some.isupper())
print("A expressão: ",some,", pode ser um número? ",some.isnumeric())
print("A expressão: ",some,", pode ser decimal? ",some.isdecimal())
