some = input("Digite algo")
print("O tipo primitivo desse valor é: {}".format(type(some)))
print("A expressão: ",some,", pode ser um alfanumérico? ",some.isalnum())
print("A expressão: ",some,", pode ser uma letra ",some.isalpha())
print("A expressão: ",some,", pode estar em maiúsculo? ",some.isupper())
print("A expressão: ",some,", pode ser um número? ",some.isnumeric())
print("A expressão: ",some,", pode ser decimal? ",some.isdecimal())
print("A expressão: ",some,", tem espaço? ",some.isspace())
print("A expressão: ",some,", está capitalizada? ",some.istitle())